### ISSUE TITLE
Refactor `vimclj.html` to use Hiccup 2.0?

### ISSUE THREAD

**Issue by stelcodes** [liquidz/clj-vimhelp#5]
Hi there, I love this library! Thanks so much for writing the parser. I'm interested in using it as a kind of plugin to a static site generator I'm writing.

The main issue I'm running into is that my project uses Hiccup's newer `hiccup2.core` namespace which is fundamentally incompatible with the Hiccup generated by this library. Hiccup 2.0's `hiccup2.core/html` macro escapes all strings in the Hiccup by default. The way to insert a raw HTML string is to use the `hiccup2.core/raw` function which creates a special `hiccup.util.RawString` object which informs the Hiccup compiler that the string should not be escaped.

Since this library uses manual string escaping with `hiccup.core/h`, there's just no way for me to use the `vimclj.html/render*` multimethod effectively. The mix of escaped and unescaped strings in the output will all get escaped when I call `hiccup2.core/html`.

The `hiccup2.core` approach is cleaner IMO because you can avoid ever running into a situation where you unintentionally escape a string twice.

I'm wondering if you would be open to refactoring this library to use Hiccup 2.0, or if that's just out of scope. This library is already perfect for the vim iced docs. I love the look of https://liquidz.github.io/vim-iced/vim-iced.html

I've already made the necessary changes to `vimhelp.html/render*` to fix my issue but it breaks `vimhelp.html/render`. If you're interested I could try to change `vimhelp.html/render` as well but I don't need that function for my use case.

**Comment by stelcodes** [comment]
I just gave it a shot and I believe I successfully patched `vimhelp.html/render`. I'll compare the output of `make demo-clj` between branches to make sure.

**Comment by liquidz** [comment]
@stelcodes Sorry for late reply and thank for your suggestion!

Your suggestion looks reasonable and good to me.
Why don't you reopen #6?

**Comment by stelcodes** [comment]
Ok cool! And weird I did not mean to close it. I might have hit a button on accident.

**Comment by stelcodes** [comment]
Ohh I know what happened. I deleted my original fork but I shouldn't have. I'll have to make a new PR.

**Comment by liquidz** [comment]
@stelcodes Just released v1.1.0. Thank you so much!
https://github.com/liquidz/clj-vimhelp/releases/tag/1.1.0
